name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools"
          sdkmanager "platforms;android-33"
          sdkmanager "build-tools;33.0.2"
          sdkmanager "cmdline-tools;latest"

      - name: Check Android tools
        run: |
          echo $ANDROID_HOME
          which aidl || true
          find $ANDROID_HOME -name aidl

      - name: Install Build dependencies
        run: |
          sudo apt update
          sudo apt install -y \
          zip \
          unzip \
          autoconf \
          automake \
          libtool \
          pkg-config \
          libffi-dev \
          libssl-dev

          pip install --upgrade pip
          pip install cython==0.29.36
          pip install buildozer

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Car-Racing-Game-APK
          path: bin/*.apk
